apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-webserver-rolebinding
subjects:
- kind: ServiceAccount
  name: airflow-webserver-serviceaccount
roleRef:
  kind: Role
  name: airflow-webserver-role
  apiGroup: rbac.authorization.k8s.io

